// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
    "github.com/stormtrooper01/cse_lab3/server/scenarios"
)

func ComposeApiServer(port HttpPortNumber) (*BankingApiServer, error) {
    db, err := NewDbConnection()
    if err != nil {
        return nil, err
    }
    dataBase := scenarios.NewDataBase(db)
    httpHandlerFunc := scenarios.HttpHandler(dataBase)
    bankingApiServer := &BankingApiServer{
        Port:           port,
        BankingHandler: httpHandlerFunc,
    }
    return bankingApiServer, nil
}

